var express = require ("express");
const bodyParser = require('body-parser');
// const cookieParser = require('cookie-parser');
const getIndex = require('./routers/page/index.route');
const getCategoryDetails = require('./routers/page/categoryDetails.router');
const getCategory = require('./routers/page/category.router');
const adminProduct = require('./routers/admin/index.route');
const getWriter= require('./routers/page/writer.router');
const getEditor= require('./routers/page/editor.router');
const mysql = require('./model/model');
var app = express();
app.use(express.static("public"));
app.set("view engine","ejs");
app.set("views","./views");
var server = require("http").Server(app);
var io = require("socket.io")(server);
server.listen(3000);
app.use("/",getIndex);
app.use("/admin/index",adminProduct);
app.use('/category',getCategory);
app.use('/category-details',getCategoryDetails);
app.use('/writer',getWriter);
app.use('/editor',getEditor);