const express = require('express');
var bodyParser = require('body-parser');
var urlencodedParser = bodyParser.urlencoded({ extended: false });
const controller= require('../../controllers/admin/tag.controller');
var router = express.Router();
router.get('/',controller.tag);
router.post('/addTag',urlencodedParser,controller.addTag);
router.post('/edit/:id',urlencodedParser,controller.editTag);
router.get('/deleteTag/:id',controller.deleteTag);
module.exports = router;